sudo: required
language: cpp
services:
  - docker

env:
  global:
    - toolset_branch: master
    - server_type: travis
    - ros_release_name: kinetic
    - ubuntu_version_name: xenial
    - used_modules: check_cache, check_build, software_tests, code_style_check, check_deb_make, codecov_tool
    - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
  - gem install coveralls-lcov
script: 
  - source .ci_config/travis.sh
